export const navigation = [
  { href: '/', key: 'home', label: 'Overview' },
  { href: '/challenge/', key: 'challenge', label: 'First challenge' },
  { href: '/lab/', key: 'lab', label: 'Lab' },
  { href: '/graph/', key: 'graph', label: 'Graph' },
  { href: '/agents/', key: 'agents', label: 'Agents' },
  { href: '/method/', key: 'method', label: 'Method' },
  { href: '/learn/', key: 'learn', label: 'Learn' },
  { href: '/roadmap/', key: 'roadmap', label: 'Roadmap' },
  { href: '/contribute/', key: 'contribute', label: 'Join' },
];

const spacetimeSourceCards = `
  <div class="source-grid">
    <a class="source-card" href="https://www.einsteintoolkit.org/" rel="noreferrer">
      <span class="eyebrow">Existing ecosystem</span><strong>Einstein Toolkit</strong>
      <span>Open community infrastructure for computational relativistic astrophysics and gravitational physics.</span>
    </a>
    <a class="source-card" href="https://www.grchombo.org/" rel="noreferrer">
      <span class="eyebrow">Existing ecosystem</span><strong>GRChombo / GRTL</strong>
      <span>Open numerical-relativity software for dynamical strong-gravity research.</span>
    </a>
    <a class="source-card" href="https://arxiv.org/abs/2404.03095" rel="noreferrer">
      <span class="eyebrow">Related research</span><strong>Warp Factory</strong>
      <span>A numerical framework for evaluating proposed warp-drive spacetime geometries.</span>
    </a>
    <a class="source-card" href="https://www.nasa.gov/humans-in-space/humans-to-mars/" rel="noreferrer">
      <span class="eyebrow">Benchmark context</span><strong>NASA: Humans to Mars</strong>
      <span>Public context for why Earth-to-Mars transportation remains a demanding engineering benchmark.</span>
    </a>
  </div>`;

const quietComputeSourceCards = `
  <div class="source-grid quiet-source-grid">
    <a class="source-card" href="https://www.energy.gov/cmei/femp/cooling-water-efficiency-opportunities-federal-data-centers" rel="noreferrer">
      <span class="eyebrow">Cooling boundary</span><strong>Count the entire heat-removal path</strong>
      <span>DOE guidance is why the benchmark records fans, pumps, chillers, cooling towers, liquid loops, water, and facility energy instead of measuring only the server.</span>
    </a>
    <a class="source-card" href="https://www.osha.gov/noise/" rel="noreferrer">
      <span class="eyebrow">Noise method</span><strong>Measure before claiming improvement</strong>
      <span>OSHA's measurement context supports calibrated decibel records, declared placement, background levels, uncertainty, and engineering controls.</span>
    </a>
    <a class="source-card" href="https://www.energy.gov/science/doe-explainssuperconductivity" rel="noreferrer">
      <span class="eyebrow">Materials reality</span><strong>Superconductivity is a testable branch</strong>
      <span>DOE's overview is why any materials proposal must include temperature, field, current, cooling, conversion losses, and physical validation—not only a simulation.</span>
    </a>
  </div>`;

export const pages = [
  {
    slug: '',
    key: 'home',
    title: 'TheCubedz',
    description: 'Data centers are too freaking loud. Join TheCubedz with one server, one measurement, or one reproducible idea—and help make them quiet.',
    content: `
      <main id="main-content">
        <section class="hero shell section-pad">
          <div class="hero-copy">
            <div class="status-line"><span class="status-dot"></span> Open call · servers and data centers wanted</div>
            <p class="eyebrow">Quiet Compute</p>
            <h1>Data centers are too freaking loud.</h1>
            <p class="hero-lede"><strong>Let's make them quiet.</strong> Bring one server, one measurement, or one reproducible idea. Together, we can learn what actually reduces the noise.</p>
            <div class="hero-actions">
              <a class="button primary" href="/contribute/#server-participant">Join with your server</a>
              <a class="button secondary" href="/challenge/">See the challenge</a>
            </div>
            <p class="microcopy"><strong>You stay in control:</strong> measure locally and share a declared result. Never send credentials or provide remote access. No public acoustic baseline, quieter design, or new superconductor has been verified.</p>
          </div>
          <div class="hero-visual challenge-visual" aria-label="Quiet Compute challenge scorecard">
            <div class="challenge-console">
              <div class="challenge-console-head"><span>CHALLENGE-QUIET-000001</span><strong>Every server is a data point.</strong></div>
              <div class="challenge-question">How quiet can your server get without doing less work?</div>
              <div class="challenge-console-grid">
                <div><span>Primary outcome</span><strong>Acoustic level + spectrum</strong></div>
                <div><span>Hold constant</span><strong>Useful compute</strong></div>
                <div><span>Do not hide</span><strong>Heat + energy</strong></div>
                <div><span>Do not externalize</span><strong>Water + cost</strong></div>
                <div><span>Protect</span><strong>Reliability</strong></div>
                <div><span>Require</span><strong>Independent repeat</strong></div>
              </div>
              <div class="challenge-console-foot"><span class="status-dot"></span><strong>Join the first public baseline</strong></div>
            </div>
          </div>
        </section>

        <section class="status-band" aria-label="Current project status">
          <div class="shell metric-grid">
            <div class="metric"><span>0</span><small>participating systems so far</small></div>
            <div class="metric"><span>0</span><small>published acoustic baselines</small></div>
            <div class="metric"><span data-status="candidateCount">3</span><small>evidence-protocol calibrations</small></div>
            <div class="metric"><span>0</span><small>quieter systems verified</small></div>
          </div>
        </section>

        <section class="shell section-pad split-section">
          <div>
            <p class="eyebrow">The problem in plain language</p>
            <h2>Less noise. Same work.</h2>
            <p class="section-lede">Computers make heat. Cooling that heat makes noise. We want to find every honest way to turn the sound down while the computers keep doing the same job.</p>
          </div>
          <div class="explanation-card" data-explanation-group>
            <div class="segmented" role="tablist" aria-label="Explanation level">
              <button class="segment active" type="button" data-level="simple" role="tab" aria-selected="true">Simple</button>
              <button class="segment" type="button" data-level="technical" role="tab" aria-selected="false">Technical</button>
              <button class="segment" type="button" data-level="researcher" role="tab" aria-selected="false">Researcher</button>
            </div>
            <div data-explanation="simple"><h3>Quieter is only better if the computers still work.</h3><p>Turning every fan down would reduce noise—but it could overheat the hardware. A real improvement must stay quieter during the same job without hiding the cost in higher temperature, more electricity, more water, or more failures.</p></div>
            <div data-explanation="technical" hidden><h3>Optimize acoustics under system constraints.</h3><p>For one declared rack or facility boundary, compare A-weighted sound level and spectrum under matched workloads while constraining throughput, latency, component temperatures, total facility energy, water use, reliability indicators, and cost.</p></div>
            <div data-explanation="researcher" hidden><h3>Treat this as multi-objective experimental search.</h3><p>Candidate cooling, control, power, and materials configurations move through preregistered measurement, simulation, uncertainty, adversarial, reproduction, and physical-validation gates. No single score may conceal a failed guardrail.</p></div>
          </div>
        </section>

        <section class="section-surface" id="how-it-works">
          <div class="shell section-pad">
            <p class="eyebrow">How people and computers work together</p>
            <h2>Measure. Model. Test. Repeat.</h2>
            <div class="process-grid">
              <article><span>01</span><h3>Measure the baseline</h3><p>Record sound, temperature, workload, energy, water, equipment, distance, and ambient conditions.</p></article>
              <article><span>02</span><h3>Freeze the test</h3><p>Preregister the system boundary, workload, metrics, thresholds, uncertainty, and failure conditions.</p></article>
              <article><span>03</span><h3>Propose one change</h3><p>Change one cooling, airflow, control, power, or materials variable and declare the expected mechanism.</p></article>
              <article><span>04</span><h3>Run bounded jobs</h3><p>Approved solvers and contributed hardware evaluate work units with fixed inputs and resource limits.</p></article>
              <article><span>05</span><h3>Try to disprove it</h3><p>Independent contributors repeat the result and look for shifted heat, energy, water, cost, or reliability.</p></article>
              <article><span>06</span><h3>Test hardware</h3><p>A result becomes engineering evidence only after a physical measurement matches the declared prediction.</p></article>
            </div>
          </div>
        </section>

        <section class="shell section-pad boundary-grid">
          <article class="boundary-card positive"><p class="eyebrow">What exists today</p><h2>The evidence protocol has three working calibration examples.</h2><ul class="clean-list"><li>Versioned candidates, preregistered passports, deterministic checks, and result digests.</li><li>Three known-answer spacetime calibrations with forty-three scoped checks.</li><li>Separate in-repository solver comparisons with explicit independence limits.</li><li>A public graph, challenge process, claims policy, and contribution workflow.</li></ul><a class="button secondary" href="/lab/">Inspect the protocol calibrations</a></article>
          <article class="boundary-card caution"><p class="eyebrow">What is not built yet</p><h2>The Quiet Compute instrument starts at zero.</h2><ul class="clean-list"><li>No public acoustic and thermal baseline dataset.</li><li>No frozen Quiet Compute benchmark passport or validated domain solver.</li><li>No hardware or laboratory partner is recorded.</li><li>No material—including a superconductor—has been shown here to reduce data-center noise.</li><li>Public volunteer computation remains closed until its security controls are implemented and reviewed.</li></ul></article>
        </section>

        <section class="section-surface" id="quiet-compute-contract">
          <div class="shell section-pad benchmark-layout">
            <div><p class="eyebrow">The exact first question</p><h2>Can we reduce acoustic output under a matched useful workload?</h2><p class="section-lede">The answer only counts if the test also reports temperature, energy, water, reliability, cost, uncertainty, and independent reproduction. “Quieter” cannot mean “we moved the problem somewhere else.”</p></div>
            <div class="benchmark-card"><div><span>Primary outcome</span><strong>Sound level and frequency spectrum at declared locations</strong></div><div><span>Matched condition</span><strong>The same useful compute workload and service target</strong></div><div><span>Guardrails</span><strong>Thermal, energy, water, reliability, and cost limits</strong></div><div><span>Proof</span><strong>Preregistered comparison plus independent measurement</strong></div><div><span>Current position</span><strong>Problem definition only; no Quiet Compute result is verified</strong></div></div>
          </div>
        </section>

        <section class="shell section-pad">
          <div class="section-intro"><p class="eyebrow">Join the project</p><h2>Put one server on the map.</h2><p class="section-lede narrow">One server will not answer everything. Many carefully measured servers can reveal which noise sources and fixes deserve the next experiment.</p></div>
          <div class="innovation-grid"><article><h3>Bring one server</h3><p>Run the test locally and publish sound, workload, temperature, power, equipment, and room conditions.</p><a class="button secondary" href="/contribute/#server-participant">Join with your server</a></article><article><h3>Bring one data center</h3><p>Help define realistic rack, room, cooling-plant, property-line, and community measurement boundaries.</p><a class="button secondary" href="/contribute/#server-participant">Become a measurement partner</a></article><article><h3>Bring one idea</h3><p>Propose one cooling, control, airflow, power, or materials change and say exactly what it should improve.</p><a class="button secondary" href="/contribute/">See how to contribute</a></article><article><h3>Try to break it</h3><p>Find hidden workload changes, shifted heat, missing cost, bad measurements, or results that cannot be repeated.</p><a class="button secondary" href="/method/">Read the rules</a></article></div>
        </section>

        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Built beside established evidence</p><h2>The campaign is simple. The benchmark cannot be.</h2></div>${quietComputeSourceCards}</div></section>
      </main>`,
  },
  {
    slug: 'challenge', key: 'challenge', title: 'Quiet Compute challenge',
    description: 'Data centers are too freaking loud. Join the Quiet Compute challenge with a server, a measurement, or a reproducible idea—and help make them quiet.',
    content: `
      <main id="main-content" data-page="challenge">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Quiet Compute · open call</p><h1>Data centers are too freaking loud.</h1><p class="hero-lede"><strong>Let's make them quiet.</strong> If you run a server, rack, or data center, your measurements can help us learn what makes the noise—and what actually reduces it.</p><div class="hero-actions"><a class="button primary" href="/contribute/#server-participant">Join with your server</a><a class="button secondary" href="#baseline">See what we measure</a></div><div class="quick-install" aria-label="Install the local TheCubedz research tools"><div class="quick-install-heading"><span>Install the local research tools</span><strong>LOCAL ONLY</strong></div><code id="install-linux-command">git clone --depth 1 https://github.com/chefmrfrizzle/TheCubedz.git &amp;&amp; cd TheCubedz &amp;&amp; python3.12 scripts/bootstrap.py</code><span id="install-windows-command" hidden>git clone --depth 1 https://github.com/chefmrfrizzle/TheCubedz.git; if ($LASTEXITCODE -eq 0) { Set-Location TheCubedz; py -3.12 scripts/bootstrap.py }</span><div class="quick-install-actions"><button class="button secondary" type="button" data-copy-target="#install-linux-command">Copy Linux / macOS</button><button class="button secondary" type="button" data-copy-target="#install-windows-command">Copy Windows</button><a href="/docs/QUIET_COMPUTE_NETWORK_LOGIC.md">What this installs</a></div><p>Requires Git, Python 3.12+, and Node.js 20.9+. This installs local tools only. It does not enroll a worker or upload data.</p></div></div><div class="page-status"><span class="status-dot"></span><strong>SERVER OPERATORS WANTED</strong><small>Measure locally. Keep control. Share no credentials.</small></div></section>

        <section class="section-surface"><div class="shell section-pad benchmark-layout"><div><p class="eyebrow">One problem · many paths</p><h2>First we listen. Then we test everything.</h2><p class="section-lede">Fans, pumps, airflow, cooling systems, power components, materials, workload control, and building design may all matter. We begin by measuring them the same way, then we compare one change at a time.</p></div><div class="benchmark-card"><div><span>Start small</span><strong>One declared server or rack under a repeatable workload</strong></div><div><span>Measure</span><strong>Sound, work, heat, energy, water, reliability, and cost</strong></div><div><span>Grow carefully</span><strong>Rack, room, cooling plant, property line, and community</strong></div><div><span>Count only</span><strong>Improvements another operator can repeat</strong></div></div></div></section>

        <section class="shell section-pad" id="baseline"><div class="section-intro"><p class="eyebrow">The first shared job</p><h2>Measure how loud one server really is.</h2><p class="section-lede">We need a comparable baseline before anyone can claim a fix. You run it locally; you remain in control of the machine.</p></div><div class="process-grid"><article><span>01</span><h3>Name the machine</h3><p>Record the server, accelerators, firmware, fans, pumps, cooling path, enclosure, room, and sensors.</p></article><article><span>02</span><h3>Run the same job</h3><p>Record input, duration, utilization, throughput, latency, power mode, warm-up, and steady-state window.</p></article><article><span>03</span><h3>Listen carefully</h3><p>Record sound level, frequency spectrum, distance, microphone position, calibration, and background noise.</p></article><article><span>04</span><h3>Watch the heat</h3><p>Record temperatures, energy, water if applicable, throttling, errors, and maintenance state.</p></article><article><span>05</span><h3>Do it again</h3><p>Repeat the run, preserve the raw traces, estimate uncertainty, and disclose anything excluded.</p></article><article><span>06</span><h3>Share the evidence</h3><p>Submit the declared result and digest—never credentials, remote access, or unrelated private data.</p></article></div></section>

        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Five hypothesis tracks</p><h2>Superconductors are one branch—not the assumed answer.</h2><p class="section-lede">Start with changes that can be tested quickly. Escalate to deeper materials only when the system boundary shows they could matter.</p></div><div class="gates-grid"><article><span>H1 · CONTROL</span><h3>Fan and pump control</h3><p>Optimize setpoints, fan curves, workload scheduling, and feedback control under thermal constraints.</p></article><article><span>H2 · FLOW</span><h3>Airflow and containment</h3><p>Reduce recirculation, pressure loss, turbulence, and unnecessary air movement.</p></article><article><span>H3 · LIQUID</span><h3>Direct liquid cooling</h3><p>Move heat with smaller fluid paths while accounting for pump, chiller, water, maintenance, and facility noise.</p></article><article><span>H4 · MATERIALS</span><h3>Thermal and dielectric materials</h3><p>Test interfaces, spreaders, cold plates, fluids, coatings, and phase-change systems that lower thermal resistance.</p></article><article><span>H5 · SUPERCONDUCTIVITY</span><h3>Long-horizon power materials</h3><p>Ask whether a useful superconducting component reduces total system loss after cryogenic, converter, joint, AC, cost, field, and current limits are counted.</p></article><article><span>NEGATIVE CONTROL</span><h3>Quiet but invalid</h3><p>A fan-off or workload-throttled run should fail because it violates temperature, reliability, or useful-compute constraints.</p></article></div></div></section>

        <section class="shell section-pad boundary-grid"><article class="boundary-card positive"><p class="eyebrow">A result may pass only if</p><h2>Every named guardrail survives.</h2><ul class="clean-list"><li>Acoustic output improves beyond declared measurement uncertainty.</li><li>The workload and service target are matched.</li><li>Thermal and reliability limits remain satisfied.</li><li>Energy, water, and cost effects are reported—not omitted.</li><li>A separate operator repeats the result from the frozen passport.</li></ul></article><article class="boundary-card caution"><p class="eyebrow">A result fails if</p><h2>The noise was merely moved or hidden.</h2><ul class="clean-list"><li>Compute was throttled, shortened, or changed.</li><li>Heat moved outside the measurement boundary.</li><li>Facility, pump, chiller, or cooling-tower noise was excluded without disclosure.</li><li>A material prediction lacks synthesis and physical measurement.</li><li>A simulation output is presented as an operating data-center result.</li></ul></article></section>

        <section class="shell section-pad"><div class="section-intro"><p class="eyebrow">How the work opens</p><h2>Evidence gates—not public deadlines.</h2><p class="section-lede">The project publishes what a result must prove. Operator targets, partnership timing, and internal commercialization plans do not need to sit inside the scientific participant journey.</p></div><div class="steps-grid"><div><span>GATE 01</span><h3>Install and self-test</h3><p>Recover the frozen local checks before creating or reviewing a Quiet Compute artifact.</p></div><div><span>GATE 02</span><h3>Freeze the measurement rules</h3><p>Review the units, sensor geometry, workload tolerances, guardrails, consent, and failure cases.</p></div><div><span>GATE 03</span><h3>Publish one baseline</h3><p>Release declared measurements, raw-artifact digests, uncertainty, limitations, and provenance.</p></div><div><span>GATE 04</span><h3>Reproduce before claiming</h3><p>Require unrelated operators to agree within every declared tolerance before human review.</p></div></div></section>

        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Why these rules exist</p><h2>Measure the whole system—not just the loudest fan.</h2><p class="section-lede">These sources do not prove a TheCubedz result. They explain why the first passport includes the cooling boundary, calibrated acoustics, system costs, and strict physical requirements for long-horizon materials ideas.</p></div>${quietComputeSourceCards}</div></section>
      </main>`,
  },
  {
    slug: 'lab', key: 'lab', title: 'Evidence protocol calibrations',
    description: 'Inspect the three existing spacetime calibrations that established the candidate, passport, validator, artifact, and reproduction protocol now being adapted for Quiet Compute.',
    content: `
      <main id="main-content" data-page="lab">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Existing evidence instrument</p><h1>Three spacetime tests taught the system how to preserve evidence.</h1><p class="hero-lede">These known-answer examples established the candidate, passport, deterministic-check, digest, cross-solver, and review pattern. They do not test data-center acoustics; Quiet Compute needs its own measurements and domain validators.</p></div><div class="page-status"><span class="status-dot"></span><strong data-lab-status>Loading result…</strong><small>Protocol foundation · not a Quiet Compute result or travel proposal.</small></div></section>
        <section class="shell evidence-cube-section" aria-labelledby="evidence-cube-title">
          <div class="cube-intro"><div><p class="eyebrow">The answer cube</p><h2 id="evidence-cube-title">Turn the cube to see what we know—and what we do not.</h2></div><p>Each side asks one plain question. A green answer means that check passed. It never means the whole idea has been proven.</p></div>
          <div class="evidence-cube-panel" data-evidence-cube>
            <div class="cube-stage" aria-hidden="true">
              <div class="evidence-cube" data-cube-visual data-active-face="definition">
                <div class="evidence-cube-face cube-face-front"><span>Clear setup</span></div>
                <div class="evidence-cube-face cube-face-right"><span>Basic math</span></div>
                <div class="evidence-cube-face cube-face-back"><span>Simulation</span></div>
                <div class="evidence-cube-face cube-face-left"><span>Physics meaning</span></div>
                <div class="evidence-cube-face cube-face-top"><span>Checked twice</span></div>
                <div class="evidence-cube-face cube-face-bottom"><span>Buildable</span></div>
              </div>
            </div>
            <div class="cube-inspector">
              <div class="cube-face-nav" role="tablist" aria-label="Questions answered by the cube">
                <button type="button" role="tab" aria-selected="true" data-cube-select="definition">Clear setup</button>
                <button type="button" role="tab" aria-selected="false" data-cube-select="mathematics">Basic math</button>
                <button type="button" role="tab" aria-selected="false" data-cube-select="numerics">Simulation</button>
                <button type="button" role="tab" aria-selected="false" data-cube-select="physics">Physics meaning</button>
                <button type="button" role="tab" aria-selected="false" data-cube-select="reproduction">Checked twice</button>
                <button type="button" role="tab" aria-selected="false" data-cube-select="realizability">Buildable</button>
              </div>
              <article class="cube-detail" role="tabpanel" aria-live="polite" data-cube-detail><p>Loading answer…</p></article>
            </div>
          </div>
          <div class="cube-semantic-summary" data-cube-summary aria-label="Answers to all six cube questions"></div>
        </section>
        <section class="shell lab-layout section-pad-top" id="candidate">
          <aside class="lab-sidebar"><div class="sticky-panel"><p class="eyebrow">Example being tested</p><h2 data-candidate-title>Minkowski baseline</h2><dl class="metadata-list"><div><dt>Record name</dt><dd data-candidate-id>—</dd></div><div><dt>Version</dt><dd data-candidate-version>—</dd></div><div><dt>Why it exists</dt><dd data-candidate-use>—</dd></div><div><dt>Review stage</dt><dd data-candidate-status>—</dd></div><div><dt>Test recipe</dt><dd data-validation-profile>—</dd></div></dl><button class="button primary full" type="button" data-run-crosscheck>Check the basic math here</button><a class="button secondary full" href="/data/candidate.json">See the exact data file</a><p class="fine-print">This quick browser check is for learning. The saved Python result is the project's official record.</p></div></aside>
          <div class="lab-main">
            <section class="panel" id="metric"><div class="panel-heading"><div><p class="eyebrow">The numbers behind the example</p><h2>How flat spacetime is written</h2></div><span class="scope-tag">The exact numbers we tested</span></div><div class="metric-display" data-metric-matrix aria-label="Metric matrix">Loading…</div><p class="panel-note" data-metric-conventions>These numbers only have meaning when we also state the coordinates, units, and sign rules used to read them.</p></section>
            <section class="panel browser-run"><div class="panel-heading"><div><p class="eyebrow">Try it yourself</p><h2>Five quick checks in your browser</h2></div><strong data-browser-status>Ready</strong></div><div class="progress-track"><i data-browser-progress></i></div><ol class="run-log" data-browser-log><li>Press the button to check the matrix size, shape, symmetry, determinant, and expected values.</li></ol></section>
            <section class="panel" id="result"><div class="panel-heading"><div><p class="eyebrow">Official saved test</p><h2>All 12 checks</h2></div><div class="result-summary"><strong data-pass-count>—</strong><span>passed</span><strong data-fail-count>—</strong><span>failed</span></div></div><div class="check-list" data-check-list><p>Loading the saved result…</p></div></section>
            <section class="panel fingerprint-panel" id="validator"><div><p class="eyebrow">Result ID</p><h2>A fingerprint for this exact answer</h2><code data-fingerprint>Loading…</code><p>Change any important part of the example, checker, answer, warning, or limit and this long ID changes too. That makes silent changes easier to spot.</p></div><button class="button secondary" type="button" data-copy-target="[data-fingerprint]">Copy result ID</button></section>
            <section class="two-column-panels"><article class="panel positive"><p class="eyebrow">What this test shows</p><ul class="clean-list" data-established-list><li>Loading…</li></ul></article><article class="panel caution"><p class="eyebrow">What this test does not show</p><ul class="clean-list" data-limitations-list><li>Loading…</li></ul></article></section>
            <section class="panel reproduce-panel" id="reproduce"><div><p class="eyebrow">For developers: repeat the test</p><h2>A fresh copy should produce the same result ID.</h2></div><pre><code data-reproduction-command>python scripts/research.py verify candidates/CANDIDATE-000001.json --reproducible</code></pre><button class="button secondary" type="button" data-copy-target="[data-reproduction-command]">Copy command</button><p class="panel-note">Running our code again is a repeat, not independent proof. Independent confirmation needs another person, a separate setup, and their own saved comparison.</p></section>
          </div>
        </section>
        <section class="section-surface" id="benchmark-ladder" data-benchmark-ladder>
          <div class="shell section-pad">
            <div class="section-intro"><p class="eyebrow">Benchmark 2 of the ladder</p><h2>Same space, different numbers.</h2><p class="section-lede">Coordinates are labels on a map. Stretch the labels and the number grid changes, even when the physical space does not. This test checks one declared, constant rescaling exactly.</p></div>
            <div class="coordinate-comparison">
              <article class="panel"><span class="scope-tag">Original coordinates</span><h3>t, x, y, z</h3><div class="metric-display compact-matrix" data-reference-metric aria-label="Original Minkowski metric">Loading…</div><p>One unit on each coordinate uses the original scale.</p></article>
              <div class="coordinate-equation" aria-label="Coordinate conversion"><strong>t = 2tau</strong><strong>x = 3xi</strong><strong>y = 4eta</strong><strong>z = 5zeta</strong><span>apply J<sup>T</sup> eta J</span></div>
              <article class="panel"><span class="scope-tag">Rescaled coordinates</span><h3>tau, xi, eta, zeta</h3><div class="metric-display compact-matrix" data-coordinate-metric aria-label="Rescaled Minkowski metric">Loading…</div><p>The component numbers change because the coordinate ruler changed.</p></article>
            </div>
            <div class="benchmark-verdict panel">
              <div><p class="eyebrow">Exact result</p><h3 data-coordinate-title>Loading the second benchmark…</h3><p data-coordinate-statement>The official result is loading.</p></div>
              <dl class="benchmark-facts"><div><dt>Result</dt><dd data-coordinate-status>—</dd></div><div><dt>Checks</dt><dd><span data-coordinate-pass-count>—</span> passed / <span data-coordinate-fail-count>—</span> failed</dd></div><div><dt>Separate code path</dt><dd data-coordinate-crosscheck>—</dd></div><div><dt>Scientific review</dt><dd data-coordinate-review>—</dd></div></dl>
            </div>
            <div class="boundary-grid benchmark-boundary"><article class="boundary-card positive"><p class="eyebrow">What passing proves</p><h3>One coordinate conversion works exactly.</h3><p>The primary validator passed all fourteen checks. A separate arithmetic path agrees on all thirteen checks it implements; full schema validation remains primary-only. The corrected implementation and provenance passed independent re-review.</p></article><article class="boundary-card caution"><p class="eyebrow">What passing does not prove</p><h3>This is not a general solver.</h3><p>The checker cannot infer unknown transformations, handle nonlinear coordinate maps, test arbitrary curved geometries, calculate a trip, or support a transportation claim. Implementation approval is not an outside scientific reproduction.</p></article></div>
            <div class="hero-actions"><a class="button secondary" href="/data/benchmark-000002-passport.json">Read the preregistered passport</a><a class="button secondary" href="/data/result-000002.json">Inspect all fourteen checks</a><a class="button secondary" href="/data/crosscheck-000002.json">Inspect the separate comparison</a><a class="button secondary" href="/data/review-000002.json">Read the approval record</a></div>
          </div>
        </section>
        <section class="shell section-pad" id="curved-benchmark" data-curved-benchmark>
          <div class="section-intro"><p class="eyebrow">Benchmark 3 of the ladder</p><h2>Known curvature, strict boundaries.</h2><p class="section-lede">Schwarzschild spacetime is the standard exterior geometry around an ideal spherical, non-rotating mass. Unlike the flat examples, its metric changes with position and its curvature is not zero.</p></div>
          <div class="benchmark-verdict panel">
            <div><p class="eyebrow">Preregistered result</p><h3>Can the checker recover a real curved known answer?</h3><p>Yes, inside one restricted coordinate chart: mass <code>M &gt; 0</code>, radius <code>r &gt; 2M</code>, and <code>0 &lt; theta &lt; pi</code>. The horizon boundary, central singularity, and spherical-coordinate axes are excluded.</p><code>sha256:d2b3f4a2ad15a7ade137e4aaf4166bdefab3ff33a3a2a27e5ca232c5bfb43458</code></div>
            <dl class="benchmark-facts"><div><dt>Primary result</dt><dd>17 passed / 0 failed</dd></div><div><dt>Separate solver</dt><dd>EinsteinPy matched 8/8 declared comparisons</dd></div><div><dt>Scientific review</dt><dd>REQUESTED</dd></div><div><dt>Outside signed reproduction</dt><dd>0</dd></div></dl>
          </div>
          <div class="boundary-grid benchmark-boundary"><article class="boundary-card positive"><p class="eyebrow">What passing shows</p><h3>One established curved profile is calculated correctly.</h3><p>The bound SymPy path recovered the metric inverse, determinant, connection, nonzero Riemann curvature, zero exterior Ricci and Einstein tensors, and Kretschmann scalar <code>48M²/r⁶</code>. EinsteinPy produced a matching internal comparison.</p></article><article class="boundary-card caution"><p class="eyebrow">What remains open</p><h3>This does not solve Quiet Compute—or the Mars thesis.</h3><p>No acoustic, thermal, cooling, materials, source reconstruction, geodesic trip, stability, causality, traveler safety, engineering, or novel geometry result was tested. The second solver used the same owner, machine, credentials, and Codex workflow and is unsigned.</p></article></div>
          <div class="hero-actions"><a class="button secondary" href="/data/candidate-000003.json">Read Candidate 000003</a><a class="button secondary" href="/data/benchmark-000003-passport.json">Read its passport</a><a class="button secondary" href="/data/result-000003.json">Inspect all 17 checks</a><a class="button secondary" href="/data/crosscheck-000003.json">Inspect the EinsteinPy comparison</a><a class="button secondary" href="/prompts/CANDIDATE_000003_EXTERNAL_REVIEW.md">Send the external review prompt</a></div>
        </section>
      </main>`,
  },
  {
    slug: 'graph', key: 'graph', title: 'Evidence graph and second brain',
    description: 'Explore how questions, candidates, validators, runs, claims, reproductions, and search policies connect without allowing AI output to become truth.',
    content: `
      <main id="main-content" data-page="graph">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Durable research memory</p><h1>The model is replaceable. The evidence graph is the brain.</h1><p class="hero-lede">Every relationship should answer: what is connected, why, by which source or computation, and with what review state?</p></div><div class="page-status"><span class="status-dot"></span><strong>Graph snapshot 000005</strong><small>Canonical and working-memory objects are visually separated.</small></div></section>
        <section class="shell graph-workspace section-pad-top"><div class="graph-controls"><label>Search nodes<input type="search" data-graph-search placeholder="Candidate, claim, validator…"></label><label>Filter type<select data-graph-filter><option value="all">All types</option></select></label><label class="check-control"><input type="checkbox" data-graph-canonical> Canonical only</label><span class="graph-count" data-graph-count>Loading…</span></div><div class="graph-layout"><div class="graph-canvas-wrap"><svg class="graph-canvas" data-graph-canvas viewBox="0 0 980 600" role="img" aria-label="Interactive evidence graph"></svg><noscript><p class="noscript">JavaScript is required for the interactive graph. The raw snapshot remains available at <a href="/data/knowledge-graph.json">/data/knowledge-graph.json</a>.</p></noscript></div><aside class="graph-detail" data-graph-detail><p class="eyebrow">Selected object</p><h2>Choose a node</h2><p>Inspect its type, status, authority, summary, and direct relationships.</p></aside></div><div class="graph-list" data-graph-list aria-label="Accessible graph node list"></div></section>
        <section class="section-surface" id="learning-loop"><div class="shell section-pad"><p class="eyebrow">Controlled learning loop</p><h2>Observation becomes training data only through explicit gates.</h2><div class="loop-track"><div><span>1</span><strong>Ingest</strong><small>Evidence, candidates, runs, reproductions, telemetry</small></div><div><span>2</span><strong>Validate</strong><small>Schema, provenance, license, duplication, integrity</small></div><div><span>3</span><strong>Snapshot</strong><small>Immutable named dataset with exclusions</small></div><div><span>4</span><strong>Train offline</strong><small>Retriever, ranker, surrogate, explainer, search policy</small></div><div><span>5</span><strong>Benchmark</strong><small>Frozen holdouts, calibration, regressions, safety gates</small></div><div><span>6</span><strong>Review</strong><small>Promote, reject, or roll back with a model card</small></div></div></div></section>
        <section class="shell section-pad"><p class="eyebrow">Three memory tiers</p><div class="memory-grid"><article><span class="tier tier-a">A</span><h2>Canonical science</h2><p>Versioned candidates, deterministic results, reviewed evidence, reproductions, corrections, and retractions.</p><strong>May change scientific status.</strong></article><article><span class="tier tier-b">B</span><h2>Working research</h2><p>Hypotheses, agent proposals, unresolved extractions, candidate drafts, and challenge queues.</p><strong>May propose work—not truth.</strong></article><article><span class="tier tier-c">C</span><h2>Product telemetry</h2><p>Explanation choices, failed searches, voluntary clarity ratings, and interface friction.</p><strong>May improve UX—not physics.</strong></article></div></section>
        <section class="section-surface"><div class="shell section-pad boundary-grid"><article class="boundary-card positive"><p class="eyebrow">The useful kind of learning</p><h2>Choose more informative experiments.</h2><p>A search policy can learn which candidate regions are underexplored, anomalous, expensive, redundant, or likely to produce information. Every proposal keeps the policy version and input snapshot that generated it.</p></article><article class="boundary-card caution"><p class="eyebrow">The forbidden shortcut</p><h2>Never train popularity into physical truth.</h2><p>Clicks, votes, repeated agent statements, and exciting language cannot determine whether an equation is satisfied, a solver converged, or a result was independently reproduced.</p></article></div></section>
      </main>`,
  },
  {
    slug: 'agents', key: 'agents', title: 'Bounded research agents',
    description: 'Inspect the proposed agent system, its scientific responsibilities, permissions, prohibitions, and human approval gates.',
    content: `
      <main id="main-content" data-page="agents">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Bounded agent system</p><h1>Specialists can propose work. None can promote their own claims.</h1><p class="hero-lede">The goal is not a single omniscient agent. It is a reviewable team whose permissions mirror the scientific method.</p></div><div class="page-status"><span class="status-dot"></span><strong>9 bounded roles</strong><small>Only the baseline math and explainer roles are partially implemented.</small></div></section>
        <section class="shell section-pad-top"><div class="agent-grid" data-agent-grid><p>Loading agent contracts…</p></div></section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Orchestration contract</p><h2>Every agent handoff produces a typed artifact.</h2></div><div class="orchestration-flow"><div><span>1</span><strong>Question</strong><small>research brief + scope</small></div><i>→</i><div><span>2</span><strong>Evidence</strong><small>sources + claim extracts</small></div><i>→</i><div><span>3</span><strong>Candidate</strong><small>schema + assumptions</small></div><i>→</i><div><span>4</span><strong>Validation</strong><small>solver output + limits</small></div><i>→</i><div><span>5</span><strong>Challenge</strong><small>objections + failure tests</small></div><i>→</i><div><span>6</span><strong>Review</strong><small>human status decision</small></div></div></div></section>
        <section class="shell section-pad boundary-grid"><article class="boundary-card positive"><p class="eyebrow">Agents are useful for</p><h2>Search, translation, triage, and experiment design.</h2><ul class="clean-list"><li>Finding and structuring relevant literature.</li><li>Drafting schema-conforming candidates.</li><li>Preparing deterministic solver jobs.</li><li>Finding contradictions and missing assumptions.</li><li>Explaining one result at multiple levels.</li><li>Ranking where computation may be informative next.</li></ul></article><article class="boundary-card caution"><p class="eyebrow">Agents are not allowed to</p><h2>Become the scientific authority.</h2><ul class="clean-list"><li>Invent citations or hide provenance.</li><li>Call a proposal valid before deterministic checks.</li><li>Upgrade a claim from generated prose.</li><li>Rewrite or delete canonical history.</li><li>Train on live clicks as a physics signal.</li><li>Approve their own model promotion.</li></ul></article></section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Copy-pasteable operating system</p><h2>The repository contains prompts, schemas, and authority rules for coding and research agents.</h2><p class="section-lede">Agents should receive one bounded role, explicit inputs, required outputs, forbidden actions, validation commands, and a definition of done. The orchestrator records every handoff.</p></div><a class="button primary" href="/contribute/#agent-prompts">Open the agent build prompts</a></div></section>
      </main>`,
  },
  {
    slug: 'method', key: 'method', title: 'Scientific method and claims policy',
    description: 'The methodological hypothesis, objective functions, physics gates, falsification rules, and escalating definitions of success.',
    content: `
      <main id="main-content">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Methodology</p><h1>Search the possibility space. Refuse to grade our own imagination.</h1><p class="hero-lede">The project is a laboratory notebook, a map, and a student. The notebook and map are permanent. The student can be replaced.</p></div></section>
        <section class="shell section-pad-top split-section" id="hypothesis"><div><p class="eyebrow">The hypothesis</p><h2>Systematic search may reveal useful structure in a space too large for isolated manual proposals.</h2></div><blockquote class="hypothesis-card">There may exist mathematically admissible configurations of geometry, matter, fields, and boundary conditions with transportation-relevant properties, and a reproducible computational search process may map that space more effectively than proposing one geometry at a time.</blockquote></section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">The search problem</p><h2>Optimize for information—not a predetermined wormhole.</h2></div><div class="equation-card"><code>x* = arg min<sub>x</sub> [w<sub>t</sub>T + w<sub>e</sub>E + w<sub>v</sub>V + w<sub>s</sub>S + w<sub>c</sub>C + w<sub>r</sub>R]</code><p>Travel cost, energy, physical-law violations, instability, causality problems, and engineering unrealizability remain separate terms. The weights and constraints are versioned experiment inputs—not hidden product magic.</p></div></div></section>
        <section class="shell section-pad"><div class="section-intro"><p class="eyebrow">Physics referee</p><h2>A candidate moves through independent gates.</h2></div><div class="gates-grid"><article><span>1</span><h3>Definition</h3><p>Coordinates, conventions, metric, parameters, assumptions, provenance.</p></article><article><span>2</span><h3>Mathematics</h3><p>Constraint satisfaction, convergence, residuals, coordinate consistency.</p></article><article><span>3</span><h3>Source requirements</h3><p>Stress-energy or matter model implied by the geometry.</p></article><article><span>4</span><h3>Physical constraints</h3><p>Energy conditions, quantum bounds, conservation laws.</p></article><article><span>5</span><h3>Dynamics</h3><p>Stability, perturbations, horizons, singularities, controllability.</p></article><article><span>6</span><h3>Causality</h3><p>Closed causal curves, chronology issues, global consistency.</p></article><article><span>7</span><h3>Realizability</h3><p>Known matter, fields, materials, fabrication, measurement.</p></article><article><span>8</span><h3>Experiment</h3><p>Testable prediction, uncertainty, independent observation.</p></article></div></section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Escalating success</p><h2>The project can succeed long before a transportation device exists.</h2></div><ol class="success-ladder"><li><span>0</span><div><strong>Baseline reproduction</strong><p>Known simple spacetimes produce expected properties.</p></div></li><li><span>1</span><div><strong>Benchmark recovery</strong><p>The engine recovers established candidate families it was not explicitly hard-coded to imitate.</p></div></li><li><span>2</span><div><strong>Search efficiency</strong><p>A transparent policy outperforms a defined naive baseline.</p></div></li><li><span>3</span><div><strong>Useful optimization</strong><p>The system improves a known family under declared constraints.</p></div></li><li><span>4</span><div><strong>Novel mathematical result</strong><p>A new candidate survives internal and external theoretical scrutiny.</p></div></li><li><span>5</span><div><strong>Novel reproduced result</strong><p>Independent implementations recover it within tolerance.</p></div></li><li><span>6</span><div><strong>Experimental prediction</strong><p>The theory predicts a measurable effect.</p></div></li><li><span>7</span><div><strong>Experimental support</strong><p>Independent observations support the prediction.</p></div></li></ol></div></section>
        <section class="shell section-pad boundary-grid"><article class="boundary-card positive"><p class="eyebrow">Falsification first</p><h2>Every claim carries its downgrade condition.</h2><p>A contribution is stronger when it explains what evidence, derivation, resolution test, or independent reproduction would cause the claim to be rejected.</p></article><article class="boundary-card caution"><p class="eyebrow">No universal score</p><h2>“Works” is not a scientific status.</h2><p>Mathematical consistency, physical admissibility, stability, causality, and engineering realizability remain separate assessments with different evidence.</p></article></section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Research context</p><h2>The spacetime track begins as an orchestration and evidence layer above established tools.</h2></div>${spacetimeSourceCards}</div></section>
      </main>`,
  },
  {
    slug: 'learn', key: 'learn', title: 'Learn the experiment',
    description: 'Plain-language and technical explanations of the evidence method, Quiet Compute measurement, spacetime calibration, validators, reproduction, and evidence graphs.',
    content: `
      <main id="main-content" data-page="learn">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Learn the evidence method</p><h1>The same evidence, explained at the level you need.</h1><p class="hero-lede">Quiet Compute is the first public challenge. The spacetime examples below are the existing calibration track. Across both, explanations may change vocabulary and analogy but never raw fields, status, uncertainty, provenance, or limitations.</p></div></section>
        <section class="shell section-pad-top concept-stack">
          <article class="concept-card" data-explanation-group><div class="concept-heading"><div><p class="eyebrow">Start here</p><h2>What “quieter” must mean</h2></div><div class="segmented small"><button class="segment active" data-level="simple" type="button">Simple</button><button class="segment" data-level="technical" type="button">Technical</button></div></div><div data-explanation="simple"><p>Measure sound while the same computer job runs. Also measure heat, electricity, water, errors, and cost so the noise is not merely moved or hidden.</p></div><div data-explanation="technical" hidden><p>Compare acoustic level and spectrum under matched workload and declared system boundaries while enforcing thermal, performance, energy, water, reliability, cost, uncertainty, and reproduction constraints.</p></div></article>
          <article class="concept-card" data-explanation-group><div class="concept-heading"><div><p class="eyebrow">Concept 01</p><h2>The Rubik's Cube analogy</h2></div><div class="segmented small"><button class="segment active" data-level="simple" type="button">Simple</button><button class="segment" data-level="technical" type="button">Technical</button></div></div><div data-explanation="simple"><p>Physics supplies the legal moves. A candidate is one arrangement. A validator checks only the rules it knows. Every failure colors in another part of the map.</p></div><div data-explanation="technical" hidden><p>The state space contains parameterized geometries, source models, fields, and boundary conditions. The project records validator predicates, outputs, scope, and provenance for each sampled point.</p></div></article>
          <article class="concept-card" data-explanation-group><div class="concept-heading"><div><p class="eyebrow">Concept 02</p><h2>Metric tensor</h2></div><div class="segmented small"><button class="segment active" data-level="simple" type="button">Simple</button><button class="segment" data-level="technical" type="button">Technical</button></div></div><div data-explanation="simple"><p>A mathematical rule describing how distance and time intervals are measured in a region of spacetime.</p></div><div data-explanation="technical" hidden><p>A symmetric rank-(0,2) tensor g<sub>μν</sub> defining the line element and local causal structure under declared coordinates and signature conventions.</p></div></article>
          <article class="concept-card" data-explanation-group><div class="concept-heading"><div><p class="eyebrow">Concept 03</p><h2>Stress-energy tensor</h2></div><div class="segmented small"><button class="segment active" data-level="simple" type="button">Simple</button><button class="segment" data-level="technical" type="button">Technical</button></div></div><div data-explanation="simple"><p>A ledger of energy, momentum, pressure, and stress—the things that source curvature in general relativity.</p></div><div data-explanation="technical" hidden><p>T<sub>μν</sub> encodes energy density, momentum density and flux, pressure, and shear, and appears on the source side of Einstein's field equations.</p></div></article>
          <article class="concept-card" data-explanation-group><div class="concept-heading"><div><p class="eyebrow">Concept 04</p><h2>Independent reproduction</h2></div><div class="segmented small"><button class="segment active" data-level="simple" type="button">Simple</button><button class="segment" data-level="technical" type="button">Technical</button></div></div><div data-explanation="simple"><p>Someone outside the original run tries the same test and records whether they get the same meaningful result.</p></div><div data-explanation="technical" hidden><p>A reproduction records an independent contributor, environment, implementation or solver, numerical tolerances, artifact hashes, and comparison outcome. Cross-implementation agreement is stronger than repeated execution of one code path.</p></div></article>
          <article class="concept-card" data-explanation-group><div class="concept-heading"><div><p class="eyebrow">Concept 05</p><h2>Evidence graph</h2></div><div class="segmented small"><button class="segment active" data-level="simple" type="button">Simple</button><button class="segment" data-level="technical" type="button">Technical</button></div></div><div data-explanation="simple"><p>A map showing which source supports which claim, which run tested which candidate, and which reproduction agreed or disagreed.</p></div><div data-explanation="technical" hidden><p>A typed, versioned projection from the append-only event ledger whose nodes and edges retain authority, provenance, status, and supersession semantics.</p></div></article>
        </section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Verified explanation</p><h2>Candidate 000001 report</h2><p>Switch between the committed beginner and technical reports. Both are derived from the same result digest.</p></div><div class="report-switch"><button class="button secondary active" type="button" data-report-mode="beginner">Beginner report</button><button class="button secondary" type="button" data-report-mode="technical">Technical report</button></div><article class="report-view" data-report-view><p>Loading report…</p></article></div></section>
        <section class="shell section-pad"><div class="section-intro"><p class="eyebrow">Status vocabulary</p><h2>Words should expose uncertainty rather than disguise it.</h2></div><div class="status-vocabulary"><div><span class="pill neutral">HYPOTHESIS</span><p>A testable proposition with stated assumptions.</p></div><div><span class="pill pass">COMPUTATION SUPPORTED</span><p>A versioned computation supports the statement within declared scope.</p></div><div><span class="pill neutral">REPRODUCED</span><p>An independent implementation or environment recovered the result.</p></div><div><span class="pill warning">CHALLENGED</span><p>An unresolved objection may affect interpretation or status.</p></div><div><span class="pill fail">FALSIFIED</span><p>A decisive declared test failed.</p></div><div><span class="pill fail">RETRACTED</span><p>The claim was withdrawn; its history remains visible.</p></div></div></section>
      </main>`,
  },
  {
    slug: 'roadmap', key: 'roadmap', title: 'Research roadmap',
    description: 'A benchmark-gated path from a Quiet Compute baseline to transparent design search, federated reproduction, hardware validation, and later research programs.',
    content: `
      <main id="main-content" data-page="roadmap">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Roadmap</p><h1>Earn complexity one benchmark at a time.</h1><p class="hero-lede">Quiet Compute begins with a measured server or rack—not a materials miracle. Distributed search and broader questions remain gated until the baseline, security model, and physical validation loop work.</p></div></section>
        <section class="shell section-pad-top"><div class="roadmap" data-roadmap><p>Loading roadmap…</p></div></section>
        <section class="section-surface"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">The reusable invention</p><h2>The protocol can outgrow spacetime research.</h2><p>The most transferable idea is not a wormhole. It is a disciplined loop for exploring any enormous computational possibility space.</p></div><div class="reuse-flow"><span>Candidate</span><i>→</i><span>Validator</span><i>→</i><span>Artifact</span><i>→</i><span>Graph</span><i>→</i><span>Search policy</span><i>→</i><span>Next experiment</span></div><div class="reuse-grid"><article><h3>Materials discovery</h3><p>Represent compounds, test predicted properties, preserve failed formulations, and prioritize informative experiments.</p></article><article><h3>Engineering design spaces</h3><p>Compare structures, constraints, simulations, and reproductions without hiding tradeoffs inside one score.</p></article><article><h3>Robotics policies</h3><p>Version environments, safety constraints, trials, failures, and model promotions behind frozen benchmarks.</p></article><article><h3>Mathematical exploration</h3><p>Separate conjecture generation from proof checking and keep every counterexample permanently discoverable.</p></article></div></div></section>
        <section class="shell section-pad boundary-grid"><article class="boundary-card positive"><p class="eyebrow">Scale now</p><h2>Contracts, provenance, tests, and participation.</h2><p>Portable schemas, deterministic artifacts, accessible explanations, issue templates, and independent reproduction are useful immediately.</p></article><article class="boundary-card caution"><p class="eyebrow">Scale later</p><h2>Databases, distributed solvers, models, and compute markets.</h2><p>Infrastructure is earned by measured scientific workload. V0 intentionally avoids microservices, authentication, payments, and autonomous job execution.</p></article></section>
      </main>`,
  },
  {
    slug: 'contribute', key: 'contribute', title: 'Contribute to the experiment',
    description: 'Measure, reproduce, challenge, build, explain, or govern the Quiet Compute challenge and the broader open evidence system through narrow, testable contributions.',
    content: `
      <main id="main-content" data-page="contribute">
        <section class="shell page-hero section-pad compact"><div><p class="eyebrow">Join Quiet Compute</p><h1>Put one server on the map.</h1><p class="hero-lede">Run the measurement locally. Keep control of your machine. Share the evidence that can help all of us understand why compute is so loud.</p></div><div class="page-status"><span class="status-dot"></span><strong>NO REMOTE ACCESS</strong><small>No credentials. No arbitrary public code. No hidden collection.</small></div></section>
        <section class="section-surface" id="server-participant"><div class="shell section-pad benchmark-layout"><div><p class="eyebrow">For server and data-center operators</p><h2>Bring one machine. Help build the public baseline.</h2><p class="section-lede">Start with one server or rack you can measure safely. The first participation path is a locally run, documented measurement—not handing the project control of production hardware.</p><div class="hero-actions"><a class="button primary" data-contact-link href="/CONTRIBUTING.md">Tell us about your system</a><a class="button secondary" href="/challenge/#baseline">See the measurement steps</a><a class="button secondary" href="/docs/QUIET_COMPUTE_CONTRIBUTION_TERMS_DRAFT.md">Read the draft terms</a></div></div><div class="benchmark-card"><div><span>You provide</span><strong>Declared hardware, workload, sound, temperature, power, and environment data</strong></div><div><span>You keep</span><strong>Credentials, remote access, control of the machine, and unrelated private data</strong></div><div><span>We publish</span><strong>Only the artifact scope and commercial-use permission you deliberately declare</strong></div><div><span>We do not claim</span><strong>That one server represents every data center or that a baseline proves a solution</strong></div></div></div></section>
        <section class="shell section-pad-top"><div class="contribution-grid program-tasks"><article><span>MEASURE</span><h2>Publish one baseline</h2><p>Record sound, workload, temperature, power, water if applicable, equipment, geometry, and ambient conditions.</p><a href="/challenge/#baseline">Read the baseline contract</a></article><article><span>PROPOSE</span><h2>Change one variable</h2><p>Declare one control, airflow, cooling, power, or materials change, expected mechanism, and failure conditions.</p><a data-repository-issue="candidate" href="/CONTRIBUTING.md">Open candidate guidance</a></article><article><span>CHALLENGE</span><h2>Try to break one claim</h2><p>Look for workload changes, shifted heat, missing cost, excluded sound sources, bad uncertainty, or leakage.</p><a data-repository-issue="challenge" href="/CONTRIBUTING.md">Open challenge form</a></article><article><span>REPRODUCE</span><h2>Repeat one result</h2><p>Use a separate operator or implementation and publish the environment, commands, raw traces, digest, and differences.</p><a data-repository-issue="reproduction" href="#reproduce">Open reproduction guidance</a></article><article><span>BUILD</span><h2>Add one bounded check</h2><p>Add a deterministic validator with tests, limitations, negative cases, and a reproducible command.</p><a data-repository-issue="build" href="/CONTRIBUTING.md">Open build guidance</a></article><article><span>EXPLAIN</span><h2>Explain one result</h2><p>Make an artifact understandable without changing its status, limitations, or source evidence.</p><a data-repository-issue="explain" href="/CONTRIBUTING.md">Open explanation guidance</a></article></div></section>
        <section class="section-surface" id="compute"><div class="shell section-pad benchmark-layout"><div><p class="eyebrow">Volunteer compute</p><h2>The admission and validation core now exists. Execution stays closed.</h2><p class="section-lede">The local backend verifies Ed25519-signed declarative jobs, exact runtime digests, resource limits, worker capability, replay state, independent allocation, and tolerance consensus. It produces a fail-closed isolation plan; it does not execute a public job until a reviewed runtime proves rootless, read-only, no-network enforcement.</p><div class="hero-actions"><a class="button secondary" href="/docs/QUIET_COMPUTE_NETWORK_LOGIC.md">Read the network logic</a><a class="button secondary" href="/docs/QUIET_COMPUTE_BACKEND.md">Inspect the algorithms</a></div></div><div class="benchmark-card"><div><span>Current status</span><strong>ADMISSION + PLANNING IMPLEMENTED · EXECUTION DISABLED</strong></div><div><span>Eligible work</span><strong>Signed measurement validation, comparison, and frozen reproduction jobs</strong></div><div><span>Never accepted</span><strong>Arbitrary shell commands, mutable runtimes, host mounts, privileges, or network access</strong></div><div><span>Scientific authority</span><strong>Consensus and reputation still require named human promotion</strong></div></div></div></section>
        <section class="section-surface" id="research-gates"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Existing spacetime track contract</p><h2>Eight gates remain attached to the original research program.</h2><p class="section-lede">They remain public as the first worked example of the evidence protocol. They do not automatically validate Quiet Compute; the new domain needs its own passport, measurements, solvers, and reviewers.</p></div><div class="gates-grid" data-program-gates><article><span>Loading</span><h3>Research gates</h3><p>Reading the existing program contract…</p></article></div></div></section>
        <section class="section-surface" id="reproduce"><div class="shell section-pad setup-layout"><div><p class="eyebrow">Best first contribution</p><h2>Independently reproduce Candidate 000001.</h2><p class="section-lede">Clone the repository in a clean environment, run the baseline, compare the scientific digest, and document anything that differs.</p></div><div class="terminal-card"><div class="terminal-head"><span>TERMINAL</span><button type="button" data-copy-target="[data-setup-command]">Copy all</button></div><pre><code data-setup-command>git clone YOUR_REPOSITORY_URL
cd YOUR_REPOSITORY
python -m pip install --no-build-isolation -e '.[dev]'
python scripts/research.py verify candidates/CANDIDATE-000001.json --reproducible
PYTHONPATH=src pytest
npm run check
npm run build</code></pre></div></div></section>
        <section class="shell section-pad"><div class="section-intro"><p class="eyebrow">Contribution contract</p><h2>A professional pull request explains what changed and what did not.</h2></div><div class="steps-grid"><div><span>1</span><h3>Choose one bounded problem</h3><p>Reference a candidate, claim, validator, page, schema, or issue.</p></div><div><span>2</span><h3>Declare authority</h3><p>State whether the work changes canonical evidence, working research, or product presentation.</p></div><div><span>3</span><h3>Add tests and provenance</h3><p>Include sources, methods, commands, limitations, and expected failure cases.</p></div><div><span>4</span><h3>Submit a reviewable PR</h3><p>Include reproduction commands, status implications, and generated artifacts.</p></div></div></section>
        <section class="section-surface" id="agent-prompts"><div class="shell section-pad"><div class="section-intro"><p class="eyebrow">Ordered build prompts</p><h2>Give agents a bounded job—not “solve data-center noise.”</h2><p class="section-lede">The Quiet Compute program specifies the order: scope, measurement, schema, calibration, intervention, reproduction, secure compute, and application readiness. The original spacetime program remains available as a separate research track.</p></div><div class="prompt-links" data-prompt-links><a href="/prompts/QUIET_COMPUTE_BUILD_PROGRAM.md">Quiet Compute build program</a><a href="/prompts/ORCHESTRATOR_AGENT.md">Orchestrator</a><a href="/prompts/BUILD_AGENT.md">Build agent</a><a href="/prompts/SCIENCE_AGENT.md">Science agent</a><a href="/prompts/SKEPTIC_AGENT.md">Skeptic</a><a href="/prompts/SECURITY_REVIEW_AGENT.md">Security reviewer</a><a href="/prompts/MARS_RESEARCH_PROGRAM.md">Original spacetime program</a></div></div></section>
        <section class="shell section-pad boundary-grid"><article class="boundary-card positive"><p class="eyebrow">Automatic acceptance pattern</p><h2>Narrow claim, clear evidence, reproducible artifact.</h2><p>The strongest contribution is boring to verify: its inputs are declared, its output is deterministic, its limitations are explicit, and another person can reproduce it.</p></article><article class="boundary-card caution"><p class="eyebrow">Automatic rejection pattern</p><h2>Exciting output without provenance.</h2><p>Generated metrics, summaries, simulations, or “discoveries” that cannot identify their source, method, validator, and reproducible artifact remain working-memory proposals.</p></article></section>
      </main>`,
  },
];
